store:
    clickhouse:
        hosts:
            - ${SAMPLED_CLICKHOUSE_HOST}
        username: ${SAMPLED_CLICKHOUSE_USERNAME}
        password: ${SAMPLED_CLICKHOUSE_PASSWORD}
        database: ${SAMPLED_CLICKHOUSE_DATABASE}
kafka:
    groupId: sampled_kafka_group
    resetPosition: latest
    securityProtocol: SASL_PLAINTEXT
    bootstrapServers:
        - ${SAMPLED_KAFKA_BOOTSTRAP_SERVER}
    topics:
        - ${SAMPLED_KAFKA_TOPIC}
    sasl:
        username: ${SAMPLED_KAFKA_SASL_USERNAME}
        password: ${SAMPLED_KAFKA_SASL_PASSWORD}
        mechanism: SCRAM-SHA-512
tuning:
    flushInterval: 20s
    sampleBufferSize: 1000