name: Libsampled Python Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: actions/setup-python@v2
        with:
            python-version: 3.x
      - run: pip install --upgrade pip
      - run: pip install mypy
      - run: mypy --strict libsampled/python/libsampled