name: Libsampled Python Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - run: |
          echo "Verifying tag and VERSION file agree..."
          cat VERSION | grep "$SOURCE_TAG"
          cat libsampled/python/setup.py | grep "$SOURCE_TAG"

      - uses: actions/setup-python@v2
        with:
            python-version: 3.x
      - run: pip install --upgrade pip
      - run: pip install build twine
      - run: |
          cd libsampled/python
          python3 -m build
          python3 -m twine upload --non-interactive --skip-existing -u __token__ -p ${{ secrets.PYPI_TOKEN }} dist/*
