name: Publish Images and Packages

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build Docker image
      env:
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      run: docker build . --file Dockerfile --tag boxidau/sampled-consumer:${SOURCE_TAG}
    
    - name: Push Docker image
      env:
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      run: docker push boxidau/sampled-consumer:${SOURCE_TAG}
